image: Visual Studio 2017

# version of net core
environment:
    matrix:
        - CLI_VERSION: 2.0.0

# build branches only
branches:
    only:
        - develop

build_script:
  # dotnet info
  - ps: dotnet --info
  # Run dotnet new 
  - ps: dotnet restore ./WebApp/WebApp.sln
  - ps: dotnet build ./WebApp/WebApp.sln

# send notifications
notifications:
- provider: Email
  to:
  - andriipopilevych@gmail.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true

test: off 
version: 0.0.1.{build}